### ISSUE TITLE
jekyll version needs update

### ISSUE THREAD

**Issue by zoeeer** [kacperduras/jekyll-w2m#3]
I'm just trying out this plugin. I got this Gem version conflict message on installation:

```
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (~> 3.8.5)

    jekyll-w2m was resolved to 1.0.1, which depends on
      jekyll (~> 3.7.3)
```

Maybe it's better to update the jekyll dependency, if 3.7.3 is not strictly what it depends on.
Regards!

**Comment by kacperduras** [comment]
~[rubygems](https://rubygems.org/gems/jekyll-w2m/versions/1.0.2)

Sorry for time of response :\

**Comment by zoeeer** [comment]
Thanks~
